import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Login from '../components/Login/Login'
import {useEffect, useState} from 'react'
import {supabase} from '../utils/supabaseClient'
import Account from '../components/Account'
import Footer from '../components/Footer/Footer'
import {motion, useScroll} from "framer-motion"
import SignUp from "../components/SignUp/SIgnUp";
import Loader from "../components/Loader"

export default function Home() {
    const [loading, setLoading] = useState(true)
    const [session, setSession] = useState(null)
    useEffect(() => {
        setSession(supabase.auth.session())
        supabase.auth.onAuthStateChange((_event, session) => {
            setSession(session)
        })
        //add a timer for 10 seconds to make sure the user is logged in


    }, [])


    const {scrollYProgress} = useScroll();
    return (
        <Loader>
            <motion.div
                initial={"initial"}
                animate={"animate"}
                variants={{
                    initial: {
                        opacity: 0,

                    },
                    animate: {
                        opacity: 1,
                    }
                }}
            >
                <motion.div
                    className="fixed top-0 left-0 right-0 h-2 bg-red-500 z-10"
                    style={{scaleX: scrollYProgress}}
                />
                <div>


                    <Head>
                        <title>Create Next App</title>
                        <meta name="description" content="Generated by create next app"/>
                        <link rel="icon" href="/favicon.ico"/>
                    </Head>
                    <Navbar/>

                    <div>
                       <Login/>
                    </div>
                    <div>
                        {!session ? <SignUp/> : <Account key={session.user.id} session={session}/>}
                    </div>
                    <Footer/>

                </div>
            </motion.div>
        </Loader>
    )

}
